# Generated by Django 4.1.3 on 2022-11-14 21:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_auto_20221112_0252"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car", name="description", field=ckeditor.fields.RichTextField(),
        ),
    ]
